#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID				CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID				CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID				CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID				CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID				CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID				CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
//#define RES_CINDERAPP_ICNS			CINDER_RESOURCE( ../resources/, cinderapp.icns, 144, IMAGE )
#define RES_CINDER_APP_ICON_ICO		CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 145, IMAGE )
#define RES_CORONA_PNG				CINDER_RESOURCE( ../resources/, corona.png, 146, IMAGE )
#define RES_FIELD_FRAG				CINDER_RESOURCE( ../resources/, field.frag, 147, GLSL )
#define RES_FIELD_VERT				CINDER_RESOURCE( ../resources/, field.vert, 148, GLSL )
#define RES_GLOW_PNG				CINDER_RESOURCE( ../resources/, glow.png, 149, IMAGE )
//#define RES_ICON_ICNS				CINDER_RESOURCE( ../resources/, icon.icns, 150, IMAGE )
#define RES_ICONFORCES_PNG			CINDER_RESOURCE( ../resources/, iconforces.png, 151, IMAGE )
#define RES_ICONS_PNG				CINDER_RESOURCE( ../resources/, icons.png, 152, IMAGE )
#define RES_NEBULA_PNG				CINDER_RESOURCE( ../resources/, nebula.png, 153, IMAGE )
#define RES_PASSTHRU_VERT			CINDER_RESOURCE( ../resources/, passthru.vert, 154, GLSL )
#define RES_PASSTHRUNORMALS_VERT	CINDER_RESOURCE( ../resources/, passthrunormals.vert, 155, GLSL )
#define RES_ROOM_FRAG				CINDER_RESOURCE( ../resources/, room.frag, 156, GLSL )
#define RES_ROOM_VERT				CINDER_RESOURCE( ../resources/, room.vert, 157, GLSL )
#define RES_SHARD_FRAG				CINDER_RESOURCE( ../resources/, shard.frag, 158, GLSL )
#define RES_SHARD_VERT				CINDER_RESOURCE( ../resources/, shard.vert, 159, GLSL )
/////////////////////////////////////////////
