#pragma once
#include "cinder/CinderResources.h"

//#define RES_CUBE1_ID		CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
//#define RES_CUBE2_ID		CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
//#define RES_CUBE3_ID		CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
//#define RES_CUBE4_ID		CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
//#define RES_CUBE5_ID		CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
//#define RES_CUBE6_ID		CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )

/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
#define RES_BRIGHTSTARS_FRAG				CINDER_RESOURCE( ../resources/, brightstars.frag, 140, GLSL )
#define RES_BRIGHTSTARS_VERT				CINDER_RESOURCE( ../resources/, brightstars.vert, 141, GLSL )
//#define RES_CINDERAPP_ICNS					CINDER_RESOURCE( ../resources/, cinderapp.icns, 142, IMAGE )
#define RES_CINDER_APP_ICON_ICO				CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 143, IMAGE )
#define RES_DARKSTAR_PNG					CINDER_RESOURCE( ../resources/, darkstar.png, 144, IMAGE )
#define RES_FAINTSTARS_FRAG					CINDER_RESOURCE( ../resources/, faintstars.frag, 145, GLSL )
#define RES_FAINTSTARS_VERT					CINDER_RESOURCE( ../resources/, faintstars.vert, 146, GLSL )
//#define RES_ICON_ICNS						CINDER_RESOURCE( ../resources/, icon.icns, 147, IMAGE )
#define RES_ICONCATALOG_PNG					CINDER_RESOURCE( ../resources/, iconcatalog.png, 148, IMAGE )
#define RES_MILKYWAY_JPG					CINDER_RESOURCE( ../resources/, milkyway.jpg, 149, IMAGE ) //orignal filename: ESO_-_Milky_Way.jpg  Credit: European Southern Observatory - ESO/S. Brunier
#define RES_PASSTHRU_VERT					CINDER_RESOURCE( ../resources/, passthru.vert, 150, GLSL )
#define RES_PASSTHRUNORMALS_VERT			CINDER_RESOURCE( ../resources/, passthrunormals.vert, 151, GLSL )
#define RES_ROOM_FRAG						CINDER_RESOURCE( ../resources/, room.frag, 152, GLSL )
#define RES_ROOM_VERT						CINDER_RESOURCE( ../resources/, room.vert, 153, GLSL )
#define RES_SPECTRUM_PNG					CINDER_RESOURCE( ../resources/, spectrum.png, 154, IMAGE )
#define RES_STAR_PNG						CINDER_RESOURCE( ../resources/, star.png, 155, IMAGE )
#define RES_STARDATA_TXT					CINDER_RESOURCE( ../resources/, stardata.txt, 156, TXTFILE )
#define RES_STARGLOW_PNG					CINDER_RESOURCE( ../resources/, starglow.png, 157, IMAGE )
/////////////////////////////////////////////
