#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID		CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID		CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID		CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID		CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID		CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID		CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
#define RES_CINDER_APP_ICON_ICO		CINDER_RESOURCE(../resources/, cinder_app_icon.ico, 144, IMAGE )
//#define RES_CINDERAPP_ICNS		CINDER_RESOURCE(../resources/, CinderApp.icns, 145, IMAGE )
//#define RES_ICON_ICNS				CINDER_RESOURCE(../resources/, icon.icns, 146, IMAGE )
#define RES_ICONTERRAIN_PNG			CINDER_RESOURCE(../resources/, iconTerrain.png, 147, IMAGE )
#define RES_GLOW_PNG				CINDER_RESOURCE(../resources/, glow.png, 148, IMAGE )
#define RES_GRADIENT_PNG			CINDER_RESOURCE(../resources/, gradient.png, 149, IMAGE )
#define RES_ROOMBLANK_PNG			CINDER_RESOURCE(../resources/, roomBlank.png, 150, IMAGE )
#define RES_ROOMCEILING_PNG			CINDER_RESOURCE(../resources/, roomCeiling.png, 151, IMAGE )
#define RES_ROOMFLOOR_PNG			CINDER_RESOURCE(../resources/, roomFloor.png, 152, IMAGE )
#define RES_ROOMWALL0_PNG			CINDER_RESOURCE(../resources/, roomWall0.png, 153, IMAGE )
#define RES_ROOMWALL1_PNG			CINDER_RESOURCE(../resources/, roomWall1.png, 154, IMAGE )
#define RES_SANDNORMAL_PNG			CINDER_RESOURCE(../resources/, sandNormal.png, 155, IMAGE )
#define RES_NODE_VERT				CINDER_RESOURCE(../resources/, node.vert, 156, GLSL )
#define RES_PASSTHRU_VERT			CINDER_RESOURCE(../resources/, passThru.vert, 157, GLSL )
#define RES_PASSTHRUNORMALS_VERT	CINDER_RESOURCE(../resources/, passThruNormals.vert, 158, GLSL )
#define RES_ROOM_VERT				CINDER_RESOURCE(../resources/, room.vert, 159, GLSL )
#define RES_ROOM_FRAG				CINDER_RESOURCE(../resources/, room.frag, 150, GLSL )
#define RES_SPHERE_VERT				CINDER_RESOURCE(../resources/, sphere.vert, 160, GLSL )
#define RES_TERRAIN_VERT			CINDER_RESOURCE(../resources/, terrain.vert, 161, GLSL )
