#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID				CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID				CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID				CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID				CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID				CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID				CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )

/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
#define RES_BIGGLOW0_PNG			CINDER_RESOURCE( ../resources/, bigglow0.png, 144, IMAGE )
#define RES_BIGGLOW1_PNG			CINDER_RESOURCE( ../resources/, bigglow1.png, 145, IMAGE )
//#define RES_CINDERAPP_ICNS			CINDER_RESOURCE( ../resources/, cinderapp.icns, 146, IMAGE )
#define RES_CINDER_APP_ICON_ICO		CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 147, IMAGE )
#define RES_CORONA_FRAG				CINDER_RESOURCE( ../resources/, corona.frag, 148, GLSL )
#define RES_CORONA_PNG				CINDER_RESOURCE( ../resources/, corona.png, 149, IMAGE )
#define RES_DUST_FRAG				CINDER_RESOURCE( ../resources/, dust.frag, 150, GLSL )
#define RES_GLOW_FRAG				CINDER_RESOURCE( ../resources/, glow.frag, 151, GLSL )
#define RES_GLOW_PNG				CINDER_RESOURCE( ../resources/, glow.png, 152, IMAGE )
#define RES_GRADIENT_FRAG			CINDER_RESOURCE( ../resources/, gradient.frag, 153, GLSL )
#define RES_GRID_PNG				CINDER_RESOURCE( ../resources/, grid.png, 154, IMAGE )
//#define RES_ICON_ICNS				CINDER_RESOURCE( ../resources/, icon.icns, 155, IMAGE )
#define RES_ICONSTAR_PNG			CINDER_RESOURCE( ../resources/, iconstar.png, 156, IMAGE )
#define RES_NEBULA_FRAG				CINDER_RESOURCE( ../resources/, nebula.frag, 157, GLSL )
#define RES_NEBULA_PNG				CINDER_RESOURCE( ../resources/, nebula.png, 158, IMAGE )
#define RES_PASSTHRU_VERT			CINDER_RESOURCE( ../resources/, passthru.vert, 159, GLSL )
#define RES_PASSTHRUCOLOR_VERT		CINDER_RESOURCE( ../resources/, passthrucolor.vert, 160, GLSL )
#define RES_PASSTHRUNORMALS_VERT	CINDER_RESOURCE( ../resources/, passthrunormals.vert, 161, GLSL )
#define RES_PLANET_FRAG				CINDER_RESOURCE( ../resources/, planet.frag, 162, GLSL )
#define RES_ROOM_FRAG				CINDER_RESOURCE( ../resources/, room.frag, 163, GLSL )
#define RES_ROOM_VERT				CINDER_RESOURCE( ../resources/, room.vert, 164, GLSL )
#define RES_SMALLGRID_PNG			CINDER_RESOURCE( ../resources/, smallgrid.png, 165, IMAGE )
#define RES_SPECTRUM_PNG			CINDER_RESOURCE( ../resources/, spectrum.png, 166, IMAGE )
#define RES_STAR_FRAG				CINDER_RESOURCE( ../resources/, star.frag, 167, GLSL )
#define RES_STAR_VERT				CINDER_RESOURCE( ../resources/, star.vert, 168, GLSL )
/////////////////////////////////////////////
