#pragma once
#include "cinder/CinderResources.h"

//#define RES_MY_RES			CINDER_RESOURCE( ../resources/, image_name.png, 128, IMAGE )

/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
#define RES_CINDER_APP_ICON_ICO			CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 140, IMAGE )
#define RES_FBOPOSINIT_FRAG				CINDER_RESOURCE( ../resources/, fboposinit.frag, 141, GLSL )
#define RES_FBOVELINIT_FRAG				CINDER_RESOURCE( ../resources/, fbovelinit.frag, 142, GLSL )
#define RES_ICONREPULSION_PNG			CINDER_RESOURCE( ../resources/, iconrepulsion.png, 143, IMAGE )
#define RES_PASSTHRU_VERT				CINDER_RESOURCE( ../resources/, passThru.vert, 144, GLSL )
#define RES_PASSTHRUNORMALS_VERT		CINDER_RESOURCE( ../resources/, passThruNormals.vert, 145, GLSL )
#define RES_POSITION_FRAG				CINDER_RESOURCE( ../resources/, Position.frag, 146, GLSL )
#define RES_ROOM_FRAG					CINDER_RESOURCE( ../resources/, room.frag, 147, GLSL )
#define RES_ROOM_VERT					CINDER_RESOURCE( ../resources/, room.vert, 148, GLSL )
#define RES_VBOPOS_FRAG					CINDER_RESOURCE( ../resources/, vbopos.frag, 149, GLSL )
#define RES_VBOPOS_VERT					CINDER_RESOURCE( ../resources/, vbopos.vert, 150, GLSL )
#define RES_VELOCITY_FRAG				CINDER_RESOURCE( ../resources/, velocity.frag, 151, GLSL )
/////////////////////////////////////////////
