#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID				CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID				CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID				CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID				CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID				CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID				CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )

/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
#define RES_ANCHOR_FRAG				CINDER_RESOURCE( ../resources/, anchor.frag, 144, GLSL )
#define RES_ANTIMATTER_FRAG			CINDER_RESOURCE( ../resources/, antimatter.frag, 145, GLSL )
#define RES_CHROMATICABBER_FRAG		CINDER_RESOURCE( ../resources/, chromaticabber.frag, 146, GLSL )
#define RES_CINDERAPP_ICNS			CINDER_RESOURCE( ../resources/, cinderapp.icns, 147, IMAGE )
#define RES_CINDER_APP_ICON_ICO		CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 148, IMAGE )
#define RES_GLOW_PNG				CINDER_RESOURCE( ../resources/, glow.png, 149, IMAGE )
#define RES_ICON_ICNS				CINDER_RESOURCE( ../resources/, icon.icns, 150, IMAGE )
#define RES_ICONMATTER_PNG			CINDER_RESOURCE( ../resources/, iconmatter.png, 151, IMAGE )
#define RES_MATTER_FRAG				CINDER_RESOURCE( ../resources/, matter.frag, 152, GLSL )
#define RES_PARTICLE_FRAG			CINDER_RESOURCE( ../resources/, particle.frag, 153, GLSL )
#define RES_PARTICLE_VERT			CINDER_RESOURCE( ../resources/, particle.vert, 154, GLSL )
#define RES_PASSTHRU_VERT			CINDER_RESOURCE( ../resources/, passthru.vert, 155, GLSL )
#define RES_ROOM_FRAG				CINDER_RESOURCE( ../resources/, room.frag, 156, GLSL )
#define RES_ROOM_VERT				CINDER_RESOURCE( ../resources/, room.vert, 157, GLSL )
#define RES_SHADOW_PNG				CINDER_RESOURCE( ../resources/, shadow.png, 158, IMAGE )
#define RES_SMOKE_PNG				CINDER_RESOURCE( ../resources/, smoke.png, 159, IMAGE )
#define RES_WARNING_PNG				CINDER_RESOURCE( ../resources/, warning.png, 160, IMAGE )
/////////////////////////////////////////////
