#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID				CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID				CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID				CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID				CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID				CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID				CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
//#define RES_CINDERAPP_ICNS			CINDER_RESOURCE( ../resources/, cinderapp.icns, 144, IMAGE )
#define RES_CINDER_APP_ICON_ICO		CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 145, IMAGE )
//#define RES_ICON_ICNS				CINDER_RESOURCE( ../resources/, icon.icns, 146, IMAGE )
#define RES_ROOM_FRAG				CINDER_RESOURCE( ../resources/, room.frag, 147, GLSL )
#define RES_ROOM_VERT				CINDER_RESOURCE( ../resources/, room.vert, 148, GLSL )
#define RES_SPHERE_FRAG				CINDER_RESOURCE( ../resources/, sphere.frag, 149, GLSL )
#define RES_SPHERE_VERT				CINDER_RESOURCE( ../resources/, sphere.vert, 150, GLSL )
/////////////////////////////////////////////
