#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID					CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID					CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID					CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID					CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID					CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID					CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
//#define RES_CINDERAPP_ICNS				CINDER_RESOURCE( ../resources/, cinderapp.icns, 144, IMAGE )
#define RES_CINDER_APP_ICON_ICO			CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 145, IMAGE )
#define RES_GLOW_PNG					CINDER_RESOURCE( ../resources/, glow.png, 146, IMAGE )
//#define RES_ICON_ICNS					CINDER_RESOURCE( ../resources/, icon.icns, 147, IMAGE )
#define RES_ICONSHOCKWAVES_PNG			CINDER_RESOURCE( ../resources/, iconshockwaves.png, 148, IMAGE )
#define RES_NODE_FRAG					CINDER_RESOURCE( ../resources/, node.frag, 149, GLSL )
#define RES_NODE_VERT					CINDER_RESOURCE( ../resources/, node.vert, 150, GLSL )
#define RES_PASSTHRU_VERT				CINDER_RESOURCE( ../resources/, passthru.vert, 151, GLSL )
#define RES_PASSTHRUNORMALS_VERT		CINDER_RESOURCE( ../resources/, passthrunormals.vert, 152, GLSL )
#define RES_ROOM_FRAG					CINDER_RESOURCE( ../resources/, room.frag, 153, GLSL )
#define RES_ROOM_VERT					CINDER_RESOURCE( ../resources/, room.vert, 154, GLSL )
#define RES_SHOCKWAVE_FRAG				CINDER_RESOURCE( ../resources/, shockwave.frag, 155, GLSL )
#define RES_SHOCKWAVE_VERT				CINDER_RESOURCE( ../resources/, shockwave.vert, 156, GLSL )
#define RES_SMOKE_PNG					CINDER_RESOURCE( ../resources/, smoke.png, 157, IMAGE )
/////////////////////////////////////////////
