#pragma once
#include "cinder/CinderResources.h"
//
#define RES_CUBE1_ID		CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID		CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID		CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID		CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID		CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID		CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
/////////////////////////////////////////////
// section generated by vsConverter
/////////////////////////////////////////////
#define RES_ANTIMATTER_FRAG				CINDER_RESOURCE( ../resources/, antimatter.frag, 144, GLSL )
#define RES_ANTIMATTER_VERT				CINDER_RESOURCE( ../resources/, antimatter.vert, 145, GLSL )
#define RES_BLUR_FRAG					CINDER_RESOURCE( ../resources/, blur.frag, 146, GLSL )
//#define RES_CINDERAPP_ICNS				CINDER_RESOURCE( ../resources/, cinderapp.icns, 147, IMAGE )
#define RES_CINDER_APP_ICON_ICO			CINDER_RESOURCE( ../resources/, cinder_app_icon.ico, 148, IMAGE )
#define RES_CONTRAST_FRAG				CINDER_RESOURCE( ../resources/, contrast.frag, 149, GLSL )
#define RES_GLOW_PNG					CINDER_RESOURCE( ../resources/, glow.png, 150, IMAGE )
#define RES_HAIR_FRAG					CINDER_RESOURCE( ../resources/, hair.frag, 151, GLSL )
#define RES_HAIR_VERT					CINDER_RESOURCE( ../resources/, hair.vert, 152, GLSL )
//#define RES_ICON_ICNS					CINDER_RESOURCE( ../resources/, icon.icns, 153, IMAGE )
#define RES_ICONATTRACTION_PNG			CINDER_RESOURCE( ../resources/, iconattraction.png, 154, IMAGE )
#define RES_KERNEL_PNG					CINDER_RESOURCE( ../resources/, kernel.png, 155, IMAGE )
#define RES_MATTER_FRAG					CINDER_RESOURCE( ../resources/, matter.frag, 156, GLSL )
#define RES_MATTER_VERT					CINDER_RESOURCE( ../resources/, matter.vert, 157, GLSL )
#define RES_NODES_FRAG					CINDER_RESOURCE( ../resources/, nodes.frag, 158, GLSL )
#define RES_NODES_VERT					CINDER_RESOURCE( ../resources/, nodes.vert, 159, GLSL )
#define RES_PARTICLE_FRAG				CINDER_RESOURCE( ../resources/, particle.frag, 160, GLSL )
#define RES_PARTICLE_VERT				CINDER_RESOURCE( ../resources/, particle.vert, 161, GLSL )
#define RES_PASSTHRU_VERT				CINDER_RESOURCE( ../resources/, passthru.vert, 162, GLSL )
#define RES_ROOM_FRAG					CINDER_RESOURCE( ../resources/, room.frag, 163, GLSL )
#define RES_ROOM_VERT					CINDER_RESOURCE( ../resources/, room.vert, 164, GLSL )
#define RES_SHADOW_PNG					CINDER_RESOURCE( ../resources/, shadow.png, 165, IMAGE )
#define RES_SMOKE_PNG					CINDER_RESOURCE( ../resources/, smoke.png, 166, IMAGE )
#define RES_SPECTRUM_PNG				CINDER_RESOURCE( ../resources/, spectrum.png, 167, IMAGE )
#define RES_WARNING_PNG					CINDER_RESOURCE( ../resources/, warning.png, 168, IMAGE )

/////////////////////////////////////////////
