#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID				CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID				CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID				CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID				CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID				CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID				CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
#define RES_CINDER_APP_ICON_ICO		CINDER_RESOURCE(../resources/, cinder_app_icon.ico, 144, IMAGE )
//#define RES_CINDERAPP_ICNS		CINDER_RESOURCE(../resources/, CinderApp.icns, 145, IMAGE )
//#define RES_ICON_ICNS				CINDER_RESOURCE(../resources/, icon.icns, 146, IMAGE )
#define RES_ICONBIGBANG_PNG			CINDER_RESOURCE(../resources/, iconBigBang.png, 147, IMAGE )
#define RES_PASSTHRU_VERT			CINDER_RESOURCE(../resources/, passThru.vert, 148, GLSL )
#define RES_PASSTHRUNORMALS_VERT	CINDER_RESOURCE(../resources/, passThruNormals.vert, 149, GLSL )
#define RES_ROOM_FRAG				CINDER_RESOURCE(../resources/, room.frag, 150, GLSL )
#define RES_ROOM_VERT				CINDER_RESOURCE(../resources/, room.vert, 151, GLSL )
#define RES_BALLOONS_FRAG			CINDER_RESOURCE(../resources/, balloons.frag, 152, GLSL )
#define RES_BALLOONS_VERT			CINDER_RESOURCE(../resources/, balloons.vert, 153, GLSL )
#define RES_CONFETTI_FRAG			CINDER_RESOURCE(../resources/, confetti.frag, 154, GLSL )
#define RES_CONFETTI_VERT			CINDER_RESOURCE(../resources/, confetti.vert, 155, GLSL )
